services:
  webserv:
    build:
      context: .
      args:
        WEBSERV_HOST_IP: "${WEBSERV_HOST_IP}"
    image: myimage
    container_name: webserv
    command: sleep infinity
    volumes:
      # - /home/saleunin/Desktop/Webserv/testing/docker:/Webserv
      # - ./:/workspace
      - ./siege:/opt/share
      # - ./Webserv/testing/docker/siege:/opt/share
    extra_hosts:
      - "host.docker.internal:host-gateway"