services:
  webserv:
    build: .
    image: myimage
    container_name: webserv
    command: sleep infinity
    volumes:
      - ./:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"