services:
  webserv:
    build: .
    image: myimage
    container_name: webserv
    command: sleep infinity
    volumes:
    - /home/saleunin/Desktop/Webserv/testing/docker:/Webserv
    - /home/saleunin/Desktop/Webserv/testing/docker:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"